config/routes.rb
Rails.application.routes.draw do
  get 'messages/index'

  get 'messages/show'

  get 'messages/new'

  get 'messages/edit'

  get 'messages/creat'

  get 'messages/destroy'

  get 'messages/update'

  resources :friendships do 
    resources :profiles
  end

  devise_for :users
  resources :profiles

  root 'profiles#index'
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => "User"
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  mount_uploader :image, ImageUploader
  
  def full_name
    self.first_name + ' ' + self.last_name
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :profile
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :messages
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    @friendship = Friendship.new(friendship_params)
    if @friendship.save
      flash[:notice] = "Added New friend"
      redirect_to profiles_path
    else
      flash[:error] = "Unable to add a friend"
      redirect_to root_path
    end
  end

  def new
    @friendship = Friendship.new
  end

  def destroy
  end

private

  def friendship_params
    params.require(:friendship).permit(:friend_id, :user_id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_message, only: [:show, :edit, :update, :destroy]

  def index
    @messages = Message.order(created_at: :desc)
  end

  def show
  end

  def new
    @message = current_user.messages.build
  end

  def edit
  end

  def create
    @message = current_user.messages.build(message_params)

    if @message.save
      redirect_to root_path
    else
      render "new"
  end

  def destroy
    @message.destroy
    redirect_to root_path
  end

  def update
    if @message.update(message_params)
      redirect_to message_path
    else
      render "edit"
    end
  end
    private

  def find_message
    @message = Message.find(params[:id])
  end

  def message_params
    params.require(:message).permit(:title, :description)
  end
end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show]

  def index
    @profile = Profile.find_by(user_id: current_user.id)
    @user = current_user
  end

  def show
    @profile = Profile.find(params[:id])
    @user = @profile.user
  end

  def create
    @profile = current_user.profile ? current_user.profile : current_user.build_profile


    @profile.assign_attributes(profile_params)
    if @profile.save
     redirect_to @profile
    else
      flash[:alert] = @profile.errors.full_messages.to_sentence
      render 'new'
    end
  end

  def new
    @profile = Profile.new 
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])
    if @profile.update(profile_params)
      redirect_to @profile
    else
      render "edit"
    end
  end

  private 

  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :bio, :image, :company)  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/friendships/destroy.html.haml
%h1 Friendships#destroy
%p Find me in app/views/friendships/destroy.html.haml

app/views/friendships/new.html.haml
= form_for @friendship do |f|
  %p
    = f.label :friend_id
    = f.text_field :friend_id
    = f.hidden_field :user_id, value: current_user.id
  %br/
  = f.submit

app/views/layouts/_sidebar.html.haml
#sidebar
  #main-nav
    #nav-container
      #profile.clearfix
        .circular
          - if @profile
            = image_tag @profile.image_url, size: "125x125"
        .title
      %ul#navigation
        %li
        - if @profile and @profile.persisted?
          %li.external
            = link_to edit_profile_path(@profile) do
              .icon.icon-book
              .text Edit Profile
        -else
        %li.external
          = link_to new_friendship_path do
            .icon.icon-paper-clip
            .text Add friend        
        %li.external
          =link_to new_profile_path do
            .icon.icon-book
            .text New Profile
        %li.external
          =link_to root_path do
            .icon.icon-repeat
            .text Memories
        %li.external
          = link_to destroy_user_session_path, method: :delete do
            .icon.icon-user
            .text Sign Out            

  .social-icons
    %ul
      %li
        %a{:href => "index.html#"}
          %i.icon-facebook
      %li
        %a{:href => "index.html#"}
          %i.icon-twitter
      %li
        %a{:href => "index.html#"}
          %i.icon-linkedin

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Memories
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body

  !!!
%html{:lang => "en"}
  %head
    %title Faculty-Responsive university staff personal page
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
      %meta{:content => "owwwlab.com", :name => "author"}
        %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1", :name => "viewport"}
          %meta{:content => "A theme for faculty profile page", :name => "description"}/
          %meta{:content => "faculty profile, theme,css, html, jquery, transition, transform, 3d, css3", :name => "keywords"}/
          %link{:href => "http://owwwlab.com/favicon.ico", :rel => "shortcut icon"}
            /[if lt IE 9]
              <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  %body
    #wrapper
      -if signed_in?  
        %a.mobilemenu{:href => "index.html#sidebar"}
          %i.icon-reorder
    - if signed_in?       
      = render 'layouts/sidebar'

    #main
      = yield

app/views/messages/_form.html.haml
= simple_form_for @message do |f|
  = f.input :title, label: "Message Title"
  = f.input :description
  = f.button :submit

app/views/messages/edit.html.haml
.col-md-8.col-md-offset-1
  %h1.new-msg-header Fix Message
  = render "form"

app/views/messages/index.html.haml
- @messages.each do |message|
  .col-md-10.col-md-offset-1
    .message
      %h2.message-title= message.title
      = link_to "Join Convo", message, class: "btn-custom"

app/views/messages/new.html.haml
.col-md-8.col-md-offset-1
  %h1.new-msg-header Post Message
  = render "form"

app/views/messages/show.html.haml
.col-md-10.col-md-offset-1
  .message-show
    %h2= @message.title
    %p.message-posted-by
      = time_ago_in_words(@message.created_at)
      ago
    %p.message-desc= @message.description
    %h3.comment-section-header Comments:
    %p= render  @message.comments
    %h3.reply-to-msg Join Discussion:
    = render 'comments/form'
    .links.btn-group
      = link_to "Back", root_path, class: "btn btn-default"
      - if user_signed_in?
        - if @message.user_id == current_user.id
          = link_to "Fix", edit_message_path(@message), class: "btn btn-primary"
          = link_to "Delete", message_path(@message), method: :delete, data: { confirm: "Are you sure ?"}, class: "btn btn-danger"

app/views/messages/update.html.haml
%h1 Messages#update
%p Find me in app/views/messages/update.html.haml

app/views/profiles/_profile.html.haml
%link{:href => "/path/to/leaflet.css", :rel => "stylesheet"}/
%script{:src => "/path/to/leaflet.js"}
    
#biography.page.home
  .pageheader
    .headercontent
      .section-container
        - if @profile
          .row
            .col-sm-2.visible-sm
            .col-sm-8.col-md-5
              .biothumb
                = image_tag @profile.image.url, class: 'img-responsive'
                .overlay
                  %ul.list-unstyled
                    %li= @profile.full_name
                    %li= @profile.company

            .clearfix.visible-sm.visible-xs
            .col-sm-12.col-md-7
              %h3.title Bio
              %p= @profile.bio
        / Button or a Link named "Send Message"
        / Clicking the "Send Message" button will show the form
        / This is done with jquery .click event show and hide
        / Form that will have textarea and a send button (Make sure its hidden use the class .hide)
        / submitting the form will save a message to the Database that will be between you and (your friend @user)
        / then redirect to this page with the message displayed

    #nav-container
      #profile.clearfix
        .circular
          - @user.friends.each do |friend|
            = link_to profile_path(friend.profile) do
              = image_tag friend.profile.image_url, size: "125x125"

app/views/profiles/edit.html.haml
= form_for @profile, multiple: true do |f|
  %p
    = f.label :first_name
    = f.text_field :first_name
  %p
    = f.label :last_name
    = f.text_field :last_name 
    %br/
  %p
    = f.label :company
    = f.text_field :company 
    %br/
  %p
    = f.label :bio
    = f.text_area :bio
    %br/
    = f.label :image                           
  = f.file_field :image
  %br/
  = f.submit

app/views/profiles/index.html.haml
= render 'profile'

app/views/profiles/update.html.haml
= render 'profile'